### ISSUE TITLE
Get last slice of datasets

### ISSUE THREAD

**Issue by willgray** [openconnectome/ocpy#3]
Investigate - may be bug in raw RESTful call (bounds checking)

**Comment by j6k4m8** [comment]
If restful bug, we can just +1 the z_stop of all downloads... Not sure if that'll result in two cube queries on the backend though.

**Comment by willgray** [comment]
Ok - confirmed that

http://openconnecto.me/ocp/ca/kasthuri11cc/hdf5/1/1,1000/1,1000/1850,1851/

works -

This means that the RESTful call is implemented properly, but we need to go
one more step in ocpy.  CAJAL may have an upper bounds check that is maxz
instead of maxz+1 like it should be...

**Comment by j6k4m8** [comment]
Good to know that between the vetted and tested post-publication framework
and the python sxript by the ugrad, the python is the part at fault...
Pushing this onto my Tuesday stack

**Comment by j6k4m8** [comment]
So @willgray the process of going one step further means that I'm requesting the last 16 slices *twice*, I believe... Unless I send a corner-case request for the last slice if `z_stop == project.z_max`..?

**Comment by alexbaden** [comment]
Confused. Explain?

**Comment by j6k4m8** [comment]
To the best of my knowledge, this is the situation:

> I want to download a project with z-range = `1..100`
> I use ocpy (or cajal or anything else) to access the hdf5 using the RESTful call
> my resultant data download stops at slice 99 (omitting the last slice)

outside the scope of ocpy, but it should be handled here as well until the bug is fixed. @willgray confirm?

**Comment by alexbaden** [comment]
So if you do (1,101), why are you downloading the last 16 slices twice?

**Comment by j6k4m8** [comment]
Because a request for (1, 101) will fail as out-of-bounds. So you have to request (1, 100), and then append the 100th slice. I *think*.

**Comment by alexbaden** [comment]
I think OCP may be inconsistent. See: https://github.com/openconnectome/open-connectome/issues/108

**Comment by j6k4m8** [comment]
this is resolved as of the latest push to pip.

**Comment by willgray** [comment]
And in CAJAL too!
